name: contacts_service
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices.
version: 0.4.8
authors:
- Lukas Dickie <lukas@changefly.com>
- Clovis Nicolas <clovisnicolas0@gmail.com>
homepage: https://github.com/lukasgit/flutter_contacts
maintainer: Lukas Dickie (@lukasgit)

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.2.2

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  quiver: ^3.0.1

flutter:
  plugin:
    androidPackage: flutter.plugins.contactsservice.contactsservice
    pluginClass: ContactsServicePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
